### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by Abbe98** [geografa/orienteering.tm2#1]
The API key seems to be invalid.

**Comment by geografa** [comment]
@abbe98 it is. It's an older example and I will be deprecating this for a newer version built in [Mapbox Studio](https://www.mapbox.com/studio/). With a Mapbox account (free), you can use your own token like this:
https://api.tiles.mapbox.com/v4/grafa.e8deadfc/page.html?access_token= `insert your token here`
